In [1]:
import torch
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6,], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [ 0,0,1],  [0,0,1],     [0,0,1],    [0,1,0],     [0,1,0],   [0,1,0],     [1,0,0],    [1,0,0] ])

In [2]:
W = torch.zeros(4,3, requires_grad= True)
b = torch.zeros(1, 3, requires_grad=True)

optimizer = torch.optim.Adam([W,b], lr=0.1)

for epoch in range(3001):
    hypothesis = torch.softmax(torch.mm(x_train, W) + b, dim = 1)
    cost = -(y_train * torch.log(hypothesis)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 300 == 0:
      print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105262
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [3]:
W

tensor([[-15.2253,   5.8876,   7.3765],
        [ -0.6394,   0.4501,   0.7652],
        [ 11.6614,  -3.5366,  -9.6394],
        [ -3.3187,   2.7671,   1.3850]], requires_grad=True)

In [4]:
#x에 따른 y값 추측 결과

W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 5.5165e-19, 7.0151e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


In [5]:
# [0,0,1] -> 2, [0,1,0] -> 1, [1,0,0] ->0
import torch.nn.functional as F

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6,], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([2, 2, 2, 1,1,1,0, 0 ])

W = torch.zeros(4, 3, requires_grad= True)
b = torch.zeros(1, requires_grad=True)

optimizer = torch.optim.Adam([W,b], lr=1.1)

for epoch in range(3001):
    #hypothesis = torch.softmax(torch.mm(x_train, W) + b, dim = 1)
    #cost = -(y_train * torch.log(hypothesis)).sum(dim=1).mean()
    z = torch.mm(x_train, W) + b
    cost = F.cross_entropy(z, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 300 == 0:
      print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.063074
epoch: 600, cost: 0.024144
epoch: 900, cost: 0.012856
epoch: 1200, cost: 0.008008
epoch: 1500, cost: 0.005454
epoch: 1800, cost: 0.003932
epoch: 2100, cost: 0.002947
epoch: 2400, cost: 0.002272
epoch: 2700, cost: 0.001788
epoch: 3000, cost: 0.001431


In [6]:
# forch.nn을 활용한 cross_entropy and softmax
import torch.nn as nn

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6,], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([2, 2, 2, 1,1,1,0, 0 ])

W = torch.zeros(4, 3, requires_grad= True)
b = torch.zeros(1, requires_grad=True)

model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(), lr=1.1)

for epoch in range(3001):
    #hypothesis = torch.softmax(torch.mm(x_train, W) + b, dim = 1)
    #cost = -(y_train * torch.log(hypothesis)).sum(dim=1).mean()
    #z = torch.mm(x_train, W) + b
    z = model(x_train)
    cost = F.cross_entropy(z, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 2.215629
epoch: 100, cost: 0.077959
epoch: 200, cost: 0.039193
epoch: 300, cost: 0.023833
epoch: 400, cost: 0.016439
epoch: 500, cost: 0.012081
epoch: 600, cost: 0.009285
epoch: 700, cost: 0.007377
epoch: 800, cost: 0.006012
epoch: 900, cost: 0.004999
epoch: 1000, cost: 0.004225
epoch: 1100, cost: 0.003618
epoch: 1200, cost: 0.003133
epoch: 1300, cost: 0.002739
epoch: 1400, cost: 0.002414
epoch: 1500, cost: 0.002142
epoch: 1600, cost: 0.001912
epoch: 1700, cost: 0.001716
epoch: 1800, cost: 0.001548
epoch: 1900, cost: 0.001402
epoch: 2000, cost: 0.001274
epoch: 2100, cost: 0.001162
epoch: 2200, cost: 0.001063
epoch: 2300, cost: 0.000975
epoch: 2400, cost: 0.000897
epoch: 2500, cost: 0.000827
epoch: 2600, cost: 0.000764
epoch: 2700, cost: 0.000707
epoch: 2800, cost: 0.000655
epoch: 2900, cost: 0.000608
epoch: 3000, cost: 0.000566
